### ISSUE TITLE
做为一个非计算机相关专业且在建设工地项目部工作过一年的可以以毕业生方式应聘吗？

### ISSUE THREAD

**Issue by mantou132** [fex-team/interview-questions#5]
CSS JS HTML 都懂一部分，但并不精通，目前正在努力学习。

**Comment by zenany** [comment]
我们只看重个人能力，从你目前描述的情况看，建议先打好基础、在实践中积累经验，等觉得自己已经可以开发百度主流产品，比如网盘、相册、贴吧、知道的时候，再来应聘吧:)
